name: generate-github-contribution-snake

on:
  workflow_dispatch:
  # cập nhật hằng ngày
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVGs
        uses: Platane/snk@v3
        with:
          github_user_name: nghiaphamhb
          outputs: |
            dist/github-snake.svg?color_dots=%23ebedf0,%23fff9c4,%23fff176,%23ffd54f,%23ffca28&color_snake=%23fb8c00
            dist/github-snake-dark.svg?palette=github-dark&color_dots=%23161b22,%23ffe082,%23ffd54f,%23ffca28,%23ffb300&color_snake=%23fb8c00

      - name: Push to output-snake branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output-snake
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
